### ISSUE TITLE
Discord Detection

### ISSUE THREAD

**Issue by ElapsedDev** [storm345/ServerAssistantIssues#5]
https://pastebin.com/u68tAHH6

**Comment by storm345** [comment]
Your issue here is that this is not how the webhook built into the plugin is intended to be used. The webhook sends data in the format that you can find in the documentation (http://storm345.github.io/ServerAssistant/configuringIssueResponses.html#customWebhook) which is not what discord expects and therefore will not work.

You can however make the plugin post to discord via IFTTT.
First, follow the tutorial in the documentation for configuring the plugin to trigger IFTTT
http://storm345.github.io/ServerAssistant/configuringIssueResponses.html#IFTTT
And then follow another tutorial online for how to get IFTTT to then post a message to your discord server.
Eg. Something like this https://birdie0.github.io/discord-webhooks-guide/services/ifttt.html

Hopefully this helps
